ARG ELK_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
FROM 5d2812e0e41c

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
